### ISSUE TITLE
Java 1.7 source and target version does not work on later java versions any more

### ISSUE THREAD

**Issue by DrMichaelPetter** [goblint/g2html#3]
I need a somewhat recent java version on my computer for teaching reasons. However, when I try to build g2html, I get:
```
    [javac] Error: Quelloption 7 wird nicht mehr unterstützt. Verwenden Sie 8 oder höher.
    [javac] Error: Zieloption 7 wird nicht mehr unterstützt. Verwenden Sie 8 oder höher.
```
It turns out, that Java 1.7 source/target has been dropped already 2022 in JDK 20, as documented in [JDK-8173605](https://bugs.openjdk.org/browse/JDK-8173605).

**Comment by sim642** [comment]
This is surprising because I'm also on Java 21 and very recently modified (4b5e1bc630f2260ad3f05af557bc65f707af1a6d) and compiled g2html without any issues.
I could reproduce the problem after wiping `g2html.jar` _and_ `bin/`.
